# 1. Data Loading

Loading the review data file and business file

In [0]:
review_dataset = pd.read_csv('review_2.csv')

In [0]:
review_dataset.shape

(8635403, 8)

In [0]:
review_dataset.head()

                review_id                 user_id  ... cool                 date
0  lWC-xP3rd6obsecCYsGZRg  ak0TdVmGKo4pwqdJSTLwWw  ...    1  2014-10-11 03:34:02
1  8bFej1QE5LXp4O05qjGqXA  YoVfDbnISlW0f7abNQACIg  ...    0  2015-07-03 20:38:25
2  NDhkzczKjLshODbqDoNLSg  eC5evKn1TWDyHCyQAwguUw  ...    0  2013-05-28 20:38:06
3  T5fAqjjFooT4V0OeZyuk1w  SFQ1jcnGguO0LYWnbbftAA  ...    1  2010-01-08 02:29:15
4  sjm_uUcQVxab_EeLCqsYLg  0kA0PAJ8QFMeveQWHFqz2A  ...    0  2011-07-28 18:05:01

[5 rows x 8 columns]

In [0]:
# conda install dask

/bin/bash: conda: command not found

In [0]:
# pip install "dask[dataframe]" --upgrade

Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.7/dist-packages (2.12.0)
Requirement already satisfied: toolz>=0.7.3 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (0.11.2)
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.1.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 5.1 MB/s
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (1.19.5)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (1.3.5)
Collecting partd>=0.3.10
  Downloading partd-1.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->dask[dataframe]) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->dask[dataframe]) (2018.9)
Collecting locket
  Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23.0->dask[dataframe]) (1.15.0)
Installing collected packages: locket, partd, fsspec
Successfully installed fsspec-2022.1.0 locket-0.2.1 partd-1.2.0

In [0]:
# print(dask_df.head())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [0]:
# #creating business database
# {
#     // string, 22 character unique string business id
#     "business_id": "tnhfDv5Il8EaGSXZGiuQGg",

#     // string, the business's name
#     "name": "Garaje",

#     // string, the full address of the business
#     "address": "475 3rd St",

#     // string, the city
#     "city": "San Francisco",

#     // string, 2 character state code, if applicable
#     "state": "CA",

#     // string, the postal code
#     "postal code": "94107",

#     // float, latitude
#     "latitude": 37.7817529521,

#     // float, longitude
#     "longitude": -122.39612197,

#     // float, star rating, rounded to half-stars
#     "stars": 4.5,

#     // integer, number of reviews
#     "review_count": 1198,

#     // integer, 0 or 1 for closed or open, respectively
#     "is_open": 1,

#     // object, business attributes to values. note: some attribute values might be objects
#     "attributes": {
#         "RestaurantsTakeOut": true,
#         "BusinessParking": {
#             "garage": false,
#             "street": true,
#             "validated": false,
#             "lot": false,
#             "valet": false
#         },
#     },

#     // an array of strings of business categories
#     "categories": [
#         "Mexican",
#         "Burgers",
#         "Gastropubs"
#     ],

#     // an object of key day to value hours, hours are using a 24hr clock
#     "hours": {
#         "Monday": "10:00-21:00",
#         "Tuesday": "10:00-21:00",
#         "Friday": "10:00-21:00",
#         "Wednesday": "10:00-21:00",
#         "Thursday": "10:00-21:00",
#         "Sunday": "11:00-18:00",
#         "Saturday": "10:00-21:00"
#     }
# }

In [0]:
%pip install -e

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-e option requires 1 argument

In [0]:
import csv
with open('business.csv', 'w', newline='') as outcsv:
    writer = csv.writer(outcsv)
    writer.writerow(["business_id", "name", "address","city","state","postal code","latitude","longitude","stars","review_count","is_open","attributes","categories","hours"])

In [0]:
import json
with open('business.csv', 'a') as csv_file:
  writer = csv.writer(csv_file)
  with open("yelp_academic_dataset_business.json", encoding="UTF-8") as json_file:
    for line in json_file:
      data = json.loads(line)
      writer.writerow([data['business_id'], data['name'],data['address'],data['city'],data['state'], data['postal_code'],data['latitude'],data['longitude'],data['stars'], data['review_count'],data['is_open'],data['attributes'],data['categories'],data['hours']])

In [0]:
df_bus = pd.read_csv('business.csv')

In [0]:
df_bus.head()

              business_id  ...                                              hours
0  6iYb2HFDywm3zjuRg0shjw  ...  {'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...
1  tCbdrRPZA0oiIYSmHG3J0w  ...  {'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...
2  bvN78flM8NLprQ1a1y5dRg  ...  {'Thursday': '11:0-18:0', 'Friday': '11:0-18:0...
3  oaepsyvc0J17qwi8cfrOWg  ...                                                NaN
4  PE9uqAjdw0E4-8mjGl3wVA  ...  {'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'...

[5 rows x 14 columns]

In [0]:
print("Columns in business data file are:")
for i in df_bus.columns:
    print(i)

Columns in business data file are:
business_id
name
address
city
state
postal code
latitude
longitude
stars
review_count
is_open
attributes
categories

In [0]:
# {
#     // string, 22 character unique user id, maps to the user in user.json
#     "user_id": "Ha3iJu77CxlrFm-vQRs_8g",

#     // string, the user's first name
#     "name": "Sebastien",

#     // integer, the number of reviews they've written
#     "review_count": 56,

#     // string, when the user joined Yelp, formatted like YYYY-MM-DD
#     "yelping_since": "2011-01-01",

#     // array of strings, an array of the user's friend as user_ids
#     "friends": [
#         "wqoXYLWmpkEH0YvTmHBsJQ",
#         "KUXLLiJGrjtSsapmxmpvTA",
#         "6e9rJKQC3n0RSKyHLViL-Q"
#     ],

#     // integer, number of useful votes sent by the user
#     "useful": 21,

#     // integer, number of funny votes sent by the user
#     "funny": 88,

#     // integer, number of cool votes sent by the user
#     "cool": 15,

#     // integer, number of fans the user has
#     "fans": 1032,

#     // array of integers, the years the user was elite
#     "elite": [
#         2012,
#         2013
#     ],

#     // float, average rating of all reviews
#     "average_stars": 4.31,

#     // integer, number of hot compliments received by the user
#     "compliment_hot": 339,

#     // integer, number of more compliments received by the user
#     "compliment_more": 668,

#     // integer, number of profile compliments received by the user
#     "compliment_profile": 42,

#     // integer, number of cute compliments received by the user
#     "compliment_cute": 62,

#     // integer, number of list compliments received by the user
#     "compliment_list": 37,

#     // integer, number of note compliments received by the user
#     "compliment_note": 356,

#     // integer, number of plain compliments received by the user
#     "compliment_plain": 68,

#     // integer, number of cool compliments received by the user
#     "compliment_cool": 91,

#     // integer, number of funny compliments received by the user
#     "compliment_funny": 99,

#     // integer, number of writer compliments received by the user
#     "compliment_writer": 95,

#     // integer, number of photo compliments received by the user
#     "compliment_photos": 50
# }

In [0]:
import csv
with open('user.csv', 'w', newline='') as outcsv:
    writer = csv.writer(outcsv)
    writer.writerow(["user_id", "name", "review_count","friends","useful","funny","cool","fans","average_stars","compliment_hot","compliment_more","compliment_profile","compliment_cute","compliment_list","compliment_note","compliment_plain","compliment_cool","compliment_funny","compliment_writer","compliment_photos"])

In [0]:
import json
with open('user.csv', 'a') as csv_file:
  writer = csv.writer(csv_file)
  with open("yelp_academic_dataset_user.json", encoding="UTF-8") as json_file:
    for line in json_file:
      data = json.loads(line)
      writer.writerow([data['user_id'], data['name'],data['review_count'],data['friends'],data['useful'], data['funny'],data['cool'],data['fans'],data['average_stars'], data['compliment_hot'],data['compliment_more'],data['compliment_profile'], data['compliment_cute'],data['compliment_list'],data['compliment_note'],data['compliment_plain'],data['compliment_cool'], data['compliment_funny'],data['compliment_writer'],data['compliment_photos']])

In [0]:
df_user = pd.read_csv('user.csv')

In [0]:
df_user.shape

(2189457, 21)

In [0]:
# {
#     // string, text of the tip
#     "text": "Secret menu - fried chicken sando is da bombbbbbb Their zapatos are good too.",

#     // string, when the tip was written, formatted like YYYY-MM-DD
#     "date": "2013-09-20",

#     // integer, how many compliments it has
#     "compliment_count": 172,

#     // string, 22 character business id, maps to business in business.json
#     "business_id": "tnhfDv5Il8EaGSXZGiuQGg",

#     // string, 22 character unique user id, maps to the user in user.json
#     "user_id": "49JhAJh8vSQ-vM4Aourl0g"
# }

In [0]:
import csv
with open('tip.csv', 'w', newline='') as outcsv:
    writer = csv.writer(outcsv)
    writer.writerow(["text","compliment_count","business_id","user_id","date"])

In [0]:
import json
with open('tip.csv', 'a') as csv_file:
  writer = csv.writer(csv_file)
  with open("yelp_academic_dataset_tip.json", encoding="UTF-8") as json_file:
    for line in json_file:
      data = json.loads(line)
      writer.writerow([data['text'], data['compliment_count'],data['business_id'],data['user_id'],data['date']])

In [0]:
tip_df=pd.read_csv('tip.csv')

In [0]:
tip_df.shape

(1162119, 5)

In [0]:
tip_df.head()

                                                text  ...                 date
0                               Carne asada chips...  ...  2011-07-22 19:07:35
1  Best happy hour from 3pm to 6pm! $1 off martin...  ...  2014-09-10 07:33:29
2  Nice people, skilled staff, clean location - b...  ...  2013-12-13 23:23:41
3  1/2-price bowling & the "Very" Old Fashion are...  ...  2017-07-11 23:07:16
4  Solid gold's. Great sauna. Great staff, too. E...  ...  2016-11-30 08:46:36

[5 rows x 5 columns]

In [0]:
import json
with open('review_2.csv', 'a') as csv_file:
  writer = csv.writer(csv_file)
  with open("yelp_academic_dataset_review.json", encoding="UTF-8") as json_file:
    for line in json_file:
      data = json.loads(line)
      writer.writerow([data['review_id'], data['user_id'],data['business_id'],data['stars'],data['useful'],data['funny'],data['cool'],data['date']])
      #sv_file.write()

# Data Preprocessing 

1)Used dask to read the huge file using multiprocessing 

2)Creeated features , handled datatypes and nulls,None,Nan etc

In [1]:
! pip install dask[dataframe] --upgrade

Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.7/dist-packages (2.12.0)
Requirement already satisfied: toolz>=0.7.3 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (0.11.2)
Collecting partd>=0.3.10
  Downloading partd-1.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (1.3.5)
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.1.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 13.8 MB/s
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from dask[dataframe]) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->dask[dataframe]) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->dask[dataframe]) (2.8.2)
Collecting locket
  Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23.0->dask[dataframe]) (1.15.0)
Installing collected packages: locket, partd, fsspec
Successfully installed fsspec-2022.1.0 locket-0.2.1 partd-1.2.0

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dask import dataframe as dd
import time
import ast
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

In [3]:
Path = '/content/drive/MyDrive/dataset'

csv = ['business.csv','review.csv','tip.csv','user.csv']

In [4]:
def csv_read(file_no):
  s_time_d = time.time()
  ddf = dd.read_csv(Path+'/'+csv[file_no])
  print('No.of partitions taken to convert to dataframe while performing parallel:',ddf.npartitions)
  e_time_d = time.time()
  print("time taken to read",e_time_d - s_time_d)
  ddf = ddf.compute()
  print(ddf.shape)
  return ddf

In [7]:
userid_to_idx = {user : idx for idx, user in enumerate(user.user_id.unique())}
businessid_to_idx = {b_id : idx for idx, b_id in enumerate(bus.business_id.unique())}

In [8]:
def idx_convertion(df,u = False ,b = False):
  if u:
    df.user_id = df.user_id.map(lambda x: userid_to_idx[x])
  if b:
    df.business_id = df.business_id.map(lambda x: businessid_to_idx[x])
    pass

In [0]:
bus = csv_read(0)
bus.head()

No.of partitions taken to convert to dataframe while performing parallel: 2
time taken to read 0.7165982723236084
(160585, 14)

              business_id  ...                                              hours
0  6iYb2HFDywm3zjuRg0shjw  ...  {'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...
1  tCbdrRPZA0oiIYSmHG3J0w  ...  {'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...
2  bvN78flM8NLprQ1a1y5dRg  ...  {'Thursday': '11:0-18:0', 'Friday': '11:0-18:0...
3  oaepsyvc0J17qwi8cfrOWg  ...                                                NaN
4  PE9uqAjdw0E4-8mjGl3wVA  ...  {'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'...

[5 rows x 14 columns]

In [0]:
filter = bus.categories.str.contains('Restaurant', na=False) | bus.categories.str.contains('Food', na=False)
bus_f = bus[filter]

In [0]:
bus_f.isnull().sum()

business_id         0
name                0
address           790
city                0
state               0
postal code        38
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes        713
categories          0
hours           10376
dtype: int64

In [0]:
bus_f.fillna(False, inplace = True)

In [0]:
val = ast.literal_eval(bus_f['attributes'].iloc[0])
cols = list(val.keys())

def add_cols(name):
  cols.remove(name)
  for i in list(ast.literal_eval(val[name]).keys()):
    cols.append(name+'_'+i)
add_cols('BusinessParking')
add_cols('Ambience')
add_cols('GoodForMeal')

cols_days = list(ast.literal_eval(bus_f['hours'].iloc[0]))
cols.extend(cols_days)
cols

['RestaurantsTableService',
 'WiFi',
 'BikeParking',
 'BusinessAcceptsCreditCards',
 'RestaurantsReservations',
 'WheelchairAccessible',
 'Caters',
 'OutdoorSeating',
 'RestaurantsGoodForGroups',
 'HappyHour',
 'BusinessAcceptsBitcoin',
 'RestaurantsPriceRange2',
 'HasTV',
 'Alcohol',
 'DogsAllowed',
 'RestaurantsTakeOut',
 'NoiseLevel',
 'RestaurantsAttire',
 'RestaurantsDelivery',
 'BusinessParking_garage',
 'BusinessParking_street',
 'BusinessParking_validated',
 'BusinessParking_lot',
 'BusinessParking_valet',
 'Ambience_touristy',
 'Ambience_hipster',
 'Ambience_romantic',
 'Ambience_divey',
 'Ambience_intimate',
 'Ambience_trendy',
 'Ambience_upscale',
 'Ambience_classy',
 'Ambience_casual',
 'GoodForMeal_dessert',
 'GoodForMeal_latenight',
 'GoodForMeal_lunch',
 'GoodForMeal_dinner',
 'GoodForMeal_brunch',
 'GoodForMeal_breakfast',
 'Monday',
 'Tuesday',
 'Wednesday',
 'Thursday',
 'Friday',
 'Saturday',
 'Sunday']

In [0]:
def dict_process(var1,var2,d,i):
  if var1 in cols:
    if isinstance(d[var2], bool) :
      att_df[var1].loc[i]=d[var2]
    elif (d[var2] == 'None') or (d[var2] == None) :
      att_df[var1].loc[i]=False
    else:
      att_df[var1].loc[i]=d[var2].lstrip('u')

def value_process(val,i):
  if val != False:
    d = ast.literal_eval(val)
    print(d)
    for j in d.keys():
      dict_process(j,j,d,i)
      if j in ['Ambience','BusinessParking','GoodForMeal']:
        d1 = ast.literal_eval(d[j])
        print(d1,d[j])
        try:
          for k in d1.keys():
            dict_process(j+'_'+k,k,d1,i)
        except:
          pass

In [0]:

att_df = pd.DataFrame(False , index = bus_f.index,columns = cols)
for i in range(bus_f.shape[0]):
  value = bus_f['attributes'].iloc[i]
  value_days = bus_f['hours'].iloc[i]
  value_process(value,i)
  value_process(value_days,i)
  
att_df

In [0]:
att_df

      RestaurantsTableService    WiFi  ...    Saturday     Sunday
0                        True  'free'  ...   11:0-23:0  11:0-23:0
1                       False  'free'  ...    5:0-18:0   5:0-18:0
5                       False  'free'  ...   11:0-22:0      False
7                       False  'free'  ...    7:0-22:0   7:0-22:0
10                      False  'free'  ...   6:30-22:0  6:30-20:0
...                       ...     ...  ...         ...        ...
60862                   False   False  ...   12:0-23:0  12:0-21:0
60863                   False    'no'  ...    11:0-0:0  11:0-23:0
60869                    True  'free'  ...  11:0-21:30  11:0-21:0
60871                    True  'free'  ...    11:0-0:0  11:0-22:0
60872                   False  'free'  ...   12:0-22:0  12:0-20:0

[63915 rows x 46 columns]

In [0]:
ll= ['RestaurantsTableService',
 'BikeParking',
 'BusinessAcceptsCreditCards',
 'RestaurantsReservations',
 'WheelchairAccessible',
 'Caters',
 'OutdoorSeating',
 'RestaurantsGoodForGroups',
 'HappyHour',
 'BusinessAcceptsBitcoin',
 'HasTV',
 'DogsAllowed',
 'RestaurantsTakeOut',
 'RestaurantsAttire',
 'RestaurantsDelivery']

for i in ll:
  att_df[i] = att_df[i].astype('bool')

In [0]:
bus_updated = pd.concat([bus_f, att_df], axis='columns')

In [0]:
bus_updated = bus_updated.drop(['categories','attributes','hours'],axis = 1)
idx_convertion(bus_updated,u=False,b=True)
bus_updated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63915 entries, 0 to 60872
Data columns (total 57 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_id                 63915 non-null  int64
 1   name                        63915 non-null  object
 2   address                     63915 non-null  object
 3   city                        63915 non-null  object
 4   state                       63915 non-null  object
 5   postal code                 63915 non-null  object
 6   latitude                    63915 non-null  float64
 7   longitude                   63915 non-null  float64
 8   stars                       63915 non-null  float64
 9   review_count                63915 non-null  int64
 10  is_open                     63915 non-null  int64
 11  RestaurantsTableService     63915 non-null  bool
 12  WiFi                        63915 non-null  object
 13  BikeParking                 63915 non-null  bool
 14  BusinessAcceptsCreditCards  63915 non-null  bool
 15  RestaurantsReservations     63915 non-null  bool
 16  WheelchairAccessible        63915 non-null  bool
 17  Caters                      63915 non-null  bool
 18  OutdoorSeating              63915 non-null  bool
 19  RestaurantsGoodForGroups    63915 non-null  bool
 20  HappyHour                   63915 non-null  bool
 21  BusinessAcceptsBitcoin      63915 non-null  bool
 22  RestaurantsPriceRange2      63915 non-null  object
 23  HasTV                       63915 non-null  bool
 24  Alcohol                     63915 non-null  object
 25  DogsAllowed                 63915 non-null  bool
 26  RestaurantsTakeOut          63915 non-null  bool
 27  NoiseLevel                  63915 non-null  object
 28  RestaurantsAttire           63915 non-null  bool
 29  RestaurantsDelivery         63915 non-null  bool
 30  BusinessParking_garage      63915 non-null  bool
 31  BusinessParking_street      63915 non-null  bool
 32  BusinessParking_validated   63915 non-null  bool
 33  BusinessParking_lot         63915 non-null  bool
 34  BusinessParking_valet       63915 non-null  bool
 35  Ambience_touristy           63915 non-null  bool
 36  Ambience_hipster            63915 non-null  bool
 37  Ambience_romantic           63915 non-null  bool
 38  Ambience_divey              63915 non-null  bool
 39  Ambience_intimate           63915 non-null  bool
 40  Ambience_trendy             63915 non-null  bool
 41  Ambience_upscale            63915 non-null  bool
 42  Ambience_classy             63915 non-null  bool
 43  Ambience_casual             63915 non-null  bool
 44  GoodForMeal_dessert         63915 non-null  bool
 45  GoodForMeal_latenight       63915 non-null  bool
 46  GoodForMeal_lunch           63915 non-null  bool
 47  GoodForMeal_dinner          63915 non-null  bool
 48  GoodForMeal_brunch          63915 non-null  bool
 49  GoodForMeal_breakfast       63915 non-null  bool
 50  Monday                      63915 non-null  object
 51  Tuesday                     63915 non-null  object
 52  Wednesday                   63915 non-null  object
 53  Thursday                    63915 non-null  object
 54  Friday                      63915 non-null  object
 55  Saturday                    63915 non-null  object
 56  Sunday                      63915 non-null  object
dtypes: bool(35), float64(3), int64(3), object(16)
memory usage: 15.4+ MB

In [0]:
bus_updated.head()
bus_updated.to_csv(Path+"/bus_updated.csv")

In [0]:
rev = csv_read(1)
idx_convertion(rev,u=True,b=True)
rev.head()

                review_id  user_id  business_id  stars
0  lWC-xP3rd6obsecCYsGZRg    92669         2999    4.0
1  8bFej1QE5LXp4O05qjGqXA   102147        15199    4.0
2  NDhkzczKjLshODbqDoNLSg   111064         3741    5.0
3  T5fAqjjFooT4V0OeZyuk1w   147370         4953    2.0
4  sjm_uUcQVxab_EeLCqsYLg     2416         3690    4.0

In [0]:
rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8635403 entries, 0 to 851618
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   review_id    object
 1   user_id      int64
 2   business_id  int64
 3   stars        float64
dtypes: float64(1), int64(2), object(1)
memory usage: 329.4+ MB

In [0]:
rev[['user_id','business_id','stars']].to_csv(Path+"/item_user.csv")

In [0]:
user =csv_read(3)
user.head()

In [9]:
idx_convertion(user,u=True,b=False)
user.head()

   user_id       name  ...  compliment_writer compliment_photos
0        0       Jane  ...                323               NaN
1        1       Gabi  ...                294               NaN
2        2      Jason  ...                  1               NaN
3        3        Kat  ...                326               NaN
4        4  Christine  ...                 44               NaN

[5 rows x 21 columns]

In [0]:
# f_df = pd.DataFrame(False,index=user.index,columns=['friend_id'])
# for i in tqdm(range(user.shape[0])):
#   if user.iloc[i,3] != 'None' :
#     flist =user.iloc[i,3].split(',')
#     #for idx, user in enumerate(user.user_id.unique()
#     id =[]
#     for j in flist:
#       var = j.lstrip(' ')
#       if var in userid_to_idx.keys():
#         id.append(userid_to_idx[var])
#     f_df['friend_id'].loc[i] = str(id)

In [10]:
user = user.drop('compliment_photos',axis=1)
user.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2189457 entries, 0 to 136439
Data columns (total 20 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             int64
 1   name                object
 2   review_count        int64
 3   friends             object
 4   useful              int64
 5   funny               int64
 6   cool                int64
 7   fans                int64
 8   average_stars       float64
 9   compliment_hot      int64
 10  is_open             int64
 11  compliment_more     int64
 12  compliment_profile  int64
 13  compliment_cute     int64
 14  compliment_list     int64
 15  compliment_note     int64
 16  compliment_plain    int64
 17  compliment_cool     int64
 18  compliment_funny    int64
 19  compliment_writer   int64
dtypes: float64(1), int64(17), object(2)
memory usage: 350.8+ MB

In [18]:
user.to_csv('/content/drive/MyDrive/dataset'+"/user_updated.csv")

In [13]:
cd /content/drive/MyDrive/dataset

/content/drive/.shortcut-targets-by-id/1_cs3LPD8H6YKA5XVThUxouQiZ4qxmZh3/dataset

In [14]:
ls

business.csv                RMnl01.h5
bus_updated.csv             tip.csv
Dataset_User_Agreement.pdf  tip_updated.csv
final_review.csv            user.csv
item_user.csv               user_updated.csv
review_2.csv                yelp_academic_dataset_business.json
review_sentiment.csv        yelp_academic_dataset_checkin.json
RM01.h5                     yelp_academic_dataset_review.json
RM02.h5                     yelp_academic_dataset_tip.json
RM03.h5                     yelp_academic_dataset_user.json
RML.h5                      yelp_database.db

In [0]:
tip =csv_read(2)

No.of partitions taken to convert to dataframe while performing parallel: 3
time taken to read 0.5661306381225586
(1162119, 5)

In [0]:
idx_convertion(tip,u=True,b=True)
tip.date = pd.to_datetime(tip.date)
tip['day'] = tip.date.dt.day
tip['month'] = tip.date.dt.month
tip['year'] = tip.date.dt.year
tip['hour'] = tip.date.dt.hour
tip['minute'] = tip.date.dt.minute
tip['second'] = tip.date.dt.second

tip.head()

                                                text  ...  second
0                               Carne asada chips...  ...      35
1  Best happy hour from 3pm to 6pm! $1 off martin...  ...      29
2  Nice people, skilled staff, clean location - b...  ...      41
3  1/2-price bowling & the "Very" Old Fashion are...  ...      16
4  Solid gold's. Great sauna. Great staff, too. E...  ...      36

[5 rows x 11 columns]

In [0]:
tip.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1162119 entries, 0 to 197906
Data columns (total 11 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   text              1162116 non-null  object
 1   compliment_count  1162119 non-null  int64
 2   business_id       1162119 non-null  int64
 3   user_id           1162119 non-null  int64
 4   date              1162119 non-null  datetime64[ns]
 5   day               1162119 non-null  int64
 6   month             1162119 non-null  int64
 7   year              1162119 non-null  int64
 8   hour              1162119 non-null  int64
 9   minute            1162119 non-null  int64
 10  second            1162119 non-null  int64
dtypes: datetime64[ns](1), int64(9), object(1)
memory usage: 106.4+ MB

In [0]:
tip.to_csv(Path+"/tip_updated.csv")

# Creating database 

Why is the need --> Loading the csv's which includes all columns and data point isn't necessary and consumes ram . to only extract the chuck of data required we creat database

In [0]:
import sqlite3 as sql
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
ls

business.csv                review_2.csv          RML-01.h5   tip.csv
bus_updated.csv             review_sentiment.csv  RML.h5      tip_updated.csv
Dataset_User_Agreement.pdf  RM01.h5               RMnl301.h5  user.csv
final_review.csv            RM02.h5               RMnlff.h5   user_updated.csv
item_user.csv               RM03.h5               RMnlf.h5    yelp_database.db

In [0]:
busdf=pd.read_csv("bus_updated.csv")

In [0]:
tipdf=pd.read_csv("tip_updated.csv")

In [0]:
tipdf.head()

   Unnamed: 0  ... second
0           0  ...     35
1           1  ...     29
2           2  ...     41
3           3  ...     16
4           4  ...     36

[5 rows x 12 columns]

In [0]:
item_user_df=pd.read_csv("review.csv")

In [0]:
item_user_df.head()

                review_id  ... stars
0  lWC-xP3rd6obsecCYsGZRg  ...   4.0
1  8bFej1QE5LXp4O05qjGqXA  ...   4.0
2  NDhkzczKjLshODbqDoNLSg  ...   5.0
3  T5fAqjjFooT4V0OeZyuk1w  ...   2.0
4  sjm_uUcQVxab_EeLCqsYLg  ...   4.0

[5 rows x 4 columns]

In [0]:
busdf1=busdf.reindex(columns= [ 'business_id', 'name', 'address', 'city', 'state',
       'postal code', 'latitude', 'longitude', 'stars', 'review_count',
       'is_open', 'RestaurantsTableService', 'BikeParking',
       'BusinessAcceptsCreditCards', 'RestaurantsReservations',
       'WheelchairAccessible', 'Caters', 'OutdoorSeating',
       'RestaurantsGoodForGroups', 'HappyHour', 'BusinessAcceptsBitcoin', 'HasTV', 'DogsAllowed',
       'RestaurantsTakeOut', 'RestaurantsAttire',
       'RestaurantsDelivery', 'BusinessParking_garage',
       'BusinessParking_street', 'BusinessParking_validated',
       'BusinessParking_lot', 'BusinessParking_valet', 'Ambience_touristy',
       'Ambience_hipster', 'Ambience_romantic', 'Ambience_divey',
       'Ambience_intimate', 'Ambience_trendy', 'Ambience_upscale',
       'Ambience_classy', 'Ambience_casual', 'GoodForMeal_dessert',
       'GoodForMeal_latenight', 'GoodForMeal_lunch', 'GoodForMeal_dinner',
       'GoodForMeal_brunch', 'GoodForMeal_breakfast','NoiseLevel', 'Alcohol',
       'RestaurantsPriceRange2','WiFi', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

In [0]:
conn = sql.connect('yelp_database.db')
busdf1.to_sql('bussiness', conn)

In [0]:
bus = pd.read_sql('SELECT * FROM bussiness limit 10', conn)

In [0]:
conn = sql.connect('yelp_database.db')
tipdf.to_sql('tips', conn)

In [0]:
review_df=pd.read_csv("final_review.csv")
review_df.to_sql('reviews', conn)

In [0]:
del review_df

In [0]:
review = pd.read_sql('select * from reviews limit 10', conn)

In [0]:
item_user=pd.read_csv('item_user.csv')

In [0]:
item_user.shape

(8635403, 4)

In [0]:
item_user.head()

   Unnamed: 0  user_id  business_id  stars
0           0    92669         2999    4.0
1           1   102147        15199    4.0
2           2   111064         3741    5.0
3           3   147370         4953    2.0
4           4     2416         3690    4.0

In [0]:
item_user.to_sql('item_user', conn)

In [0]:
del item_user

In [0]:
tip=pd.read_csv("tip_updated.csv")

In [0]:
tip.to_sql('tips', conn)

In [0]:
del tip

In [0]:
user=pd.read_csv("user_updated.csv")

In [0]:
user.to_sql('users', conn)

In [0]:
user.head()

   Unnamed: 0  user_id  ... compliment_funny  compliment_writer
0           0        0  ...              815                323
1           1        1  ...              472                294
2           2        2  ...                3                  1
3           3        3  ...              391                326
4           4        4  ...               98                 44

[5 rows x 21 columns]

In [0]:
con = sql.connect("yelp_database.db")
cursor = con.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

In [0]:
print(cursor.fetchall())

[('bussiness',), ('reviews',), ('item_user',), ('tips',), ('users',)]

In [0]:
ls

business.csv                RMnl01.h5
bus_updated.csv             tip.csv
Dataset_User_Agreement.pdf  tip_updated.csv
final_review.csv            user.csv
item_user.csv               yelp_academic_dataset_business.json
review_2.csv                yelp_academic_dataset_checkin.json
review_sentiment.csv        yelp_academic_dataset_review.json
RM01.h5                     yelp_academic_dataset_tip.json
RM02.h5                     yelp_academic_dataset_user.json
RM03.h5                     yelp_database.db
RML.h5